#!/bin/bash
# ============================================
# CONFIGURATION SYNCHRONIZATION
# ============================================
# One-way sync: ~/ configs → repo (backup/versioning)
# Home configs are the source of truth.
# Use install-configs.sh separately to restore repo → ~/
#
# Usage:
#   ./sync-configs.sh           # Sync + commit + push
#   ./sync-configs.sh --no-push # Sync + commit without push
#   ./sync-configs.sh --dry-run # Show what would be copied
# ============================================

set -e

# Ensure PATH is set for cron environment
export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

DO_PUSH=true
DRY_RUN=false

for arg in "$@"; do
    case "$arg" in
        --no-push) DO_PUSH=false ;;
        --dry-run) DRY_RUN=true ;;
    esac
done

sync_file() {
    local source="$1"
    local target="$2"
    
    if [ ! -f "$source" ] && [ ! -d "$source" ]; then
        log_warn "Source not found: $source (skipping)"
        return 0
    fi
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] $source → $target"
        return 0
    fi
    
    if [ -d "$source" ]; then
        mkdir -p "$target"
        rsync -a --delete "$source/" "$target/"
    else
        mkdir -p "$(dirname "$target")"
        cp "$source" "$target"
    fi
    
    log_info "Synced: $source"
}

# Sync Neovim config with exclusions (files generated by lazy.nvim etc.)
sync_nvim() {
    local source="$HOME/.config/nvim"
    local target="$REPO_DIR/configs/nvim"
    
    if [ ! -d "$source" ]; then
        log_warn "Source not found: $source (skipping)"
        return 0
    fi
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] $source → $target (rsync with exclusions)"
        return 0
    fi
    
    rsync -av --delete \
        --exclude='lazy-lock.json' \
        --exclude='.luarc.json' \
        --exclude='plugin/' \
        --exclude='lazy/' \
        "$source/" "$target/" > /dev/null
    
    log_info "Synced: $source (exclusions: lazy-lock.json, .luarc.json, plugin/, lazy/)"
}

# Sync LazyVim config with exclusions
sync_nvim_lazyvim() {
    local source="$HOME/.config/nvim-lazyvim"
    local target="$REPO_DIR/configs/nvim-lazyvim"

    if [ ! -d "$source" ]; then
        log_warn "Source not found: $source (skipping)"
        return 0
    fi

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] $source → $target (rsync with exclusions)"
        return 0
    fi

    rsync -av --delete \
        --exclude='lazy-lock.json' \
        --exclude='.luarc.json' \
        --exclude='.neoconf.json' \
        --exclude='plugin/' \
        --exclude='lazy/' \
        --exclude='LICENSE' \
        --exclude='README.md' \
        --exclude='.git/' \
        --exclude='.gitignore' \
        "$source/" "$target/" > /dev/null

    log_info "Synced: $source (exclusions: lazy-lock.json, .luarc.json, .neoconf.json, plugin/, lazy/)"
}

# Sync Opencode config with exclusions (node_modules, bun.lock)
sync_opencode() {
    local source="$HOME/.config/opencode"
    local target="$REPO_DIR/configs/opencode"

    if [ ! -d "$source" ]; then
        log_warn "Source not found: $source (skipping)"
        return 0
    fi

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] $source → $target (rsync with exclusions)"
        return 0
    fi

    mkdir -p "$target"
    rsync -av --delete \
        --exclude='node_modules/' \
        --exclude='bun.lock' \
        "$source/" "$target/" > /dev/null

    log_info "Synced: $source (exclusions: node_modules/, bun.lock)"
}

echo ""
echo "========================================"
echo "  CONFIG SYNCHRONIZATION"
echo "========================================"
echo ""

# Sync local configs to the repo (home is source of truth)
log_info "Syncing ~/ configs to repo..."
sync_file "$HOME/.bashrc" "$REPO_DIR/configs/bash/bashrc"
sync_file "$HOME/.config/zellij/config.kdl" "$REPO_DIR/configs/zellij/config.kdl"
sync_file "$HOME/.config/zellij/layouts" "$REPO_DIR/configs/zellij/layouts"
sync_file "$HOME/.config/zellij/themes" "$REPO_DIR/configs/zellij/themes"
sync_file "$HOME/.fzf.bash" "$REPO_DIR/configs/fzf/fzf.bash"
sync_opencode
sync_nvim
sync_nvim_lazyvim
sync_file "$HOME/.config/kitty/kitty.conf" "$REPO_DIR/configs/kitty/kitty.conf"
sync_file "$HOME/.config/starship.toml" "$REPO_DIR/configs/starship/starship.toml"

if [ "$DRY_RUN" = true ]; then
    echo ""
    log_info "Dry-run mode, no changes made"
    exit 0
fi

echo ""

# Git operations
cd "$REPO_DIR"

# Check if there are changes (including untracked files)
if git diff --quiet configs/ && git diff --cached --quiet configs/ && [ -z "$(git ls-files --others --exclude-standard configs/)" ]; then
    log_info "No changes detected"
    exit 0
fi

log_info "Committing changes..."
git add configs/
git commit -m "Sync configs - $(date '+%d/%m/%Y %H:%M')"

if [ "$DO_PUSH" = true ]; then
    log_info "Pushing to remote..."
    git push
    log_info "✅ Configs synced and pushed!"
else
    log_info "✅ Configs synced (push skipped)"
fi

echo ""
